name: deploy
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    #Para servicios usar DockerHub
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Instalar Redis
        run: sudo apt-get update -y && sudo apt-get install redis-tools -y
      - name: Test Redis
        run: redis-cli -h localhost -p 6379 ping
      - name: Mostrar Variables
        run: echo "El secreto es ${{ secrets.TOKEN_GIT }}"
      - name: Setup Node
        uses: actions/setup-node@v4  
        with:
          node-version: '18'
      